# Generated by Django 5.1.4 on 2024-12-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cuisines/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('cuisines', models.ManyToManyField(related_name='categories', to='cuisines.cuisine')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subcategories/')),
                ('categories', models.ManyToManyField(related_name='subcategories', to='cuisines.category')),
            ],
        ),
    ]
