# Generated by Django 5.1.4 on 2024-12-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisines', '0002_remove_category_cuisines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='cuisines.subcategory'),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='cuisines', to='cuisines.category'),
        ),
    ]
