# Generated by Django 5.1.4 on 2024-12-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisines', '0003_alter_category_subcategories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='cuisine_categories',
            field=models.ManyToManyField(blank=True, related_name='cuisine_categories', to='cuisines.category'),
        ),
    ]
