# Generated by Django 5.1.4 on 2024-12-13 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuisines', '0004_cuisine_cuisine_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuisine',
            name='cuisine_categories',
        ),
    ]
