# Generated by Django 5.1.4 on 2024-12-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisines', '0005_remove_cuisine_cuisine_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
