# Generated by Django 5.1.4 on 2024-12-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisines', '0006_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.BinaryField(blank=True, db_column='image', null=True),
        ),
    ]
